[build]
  functions = "functions"
  command = "netlify-lambda install && mkdir ./public"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
